### ISSUE TITLE
UL/OL Lists not Rendered after Table element

### ISSUE THREAD

**Issue by tedchuang** [briandfoy/text-multimarkdown#3]
After rendering the HTML table, subsequent UL and OL lists are not rendered as lists, but shows up as plain text instead.

**Comment by briandfoy** [comment]
Can you give an example input and the output you get? Include the program you used to test it too.

I'm able to make new releases, but I'm mostly relying on people to submit patches to fix whatever they run into.

**Comment by tedchuang** [comment]
Sorry for the late response. Below is a sample MarkDown where the bullet list won't render after table has been rendered:

```
A Line of Text:

| Date | Time | Session |
| --- | --- | --- |
| May 4 | 3:20pm |  Q&A |

* Bullet point 1
* Bullet point 2
```

**Comment by tedchuang** [comment]
Nevermind :) Just read your source code for MultiMarkdown.pm and realized that the design intent is to have 2 blank lines (or EOF) as the end-of-whole-table marker. I can easily do that. No need to change anything. Thank you for the marvelous module!!

**Comment by briandfoy** [comment]
Glad it worked out, but it's not my module or code. I'm just taking care of it for now. :)
