### ISSUE TITLE
Sorting of contents with no newline

### ISSUE THREAD

**Issue by bmartin** [briandfoy/text-multimarkdown#4]
If you call with this input:

```markdown
Current clown: Chuckles the Clown
Backup clown: Bozo the Clown (on May 31, 2026)
Update roster: update
```

The result is sorted:

```html
Backup clown: Bozo the Clown (on May 31, 2026)<br />
Current clown: Chuckles the Clown<br />
Update roster: update<br />

```

If you add an initial newline, you get a paragraph.

I don't know if the `<br />` is appropriate or the `<p>` is, but either way the output should not be sorted.

**Comment by briandfoy** [comment]
Can you show the program you used?

**Comment by guest20** [comment]
It looks like that all got slurped into the metadata hash, who's keys are sorted when the metadata is printed out

https://metacpan.org/dist/Text-MultiMarkdown/source/lib/Text/MultiMarkdown.pm#L883

**Comment by bmartin** [comment]
Sorry I missed the emails on this. Yes, it is the meta data. I fixed it in my code by adding a blank line to the start of the markdown since we were not using properties. I'm not sure if it makes sense to add it in the doc. Thanks
